// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace iOS.Storyboard
{
    public partial class HeaderPage : UIViewController
    {
        public HeaderPage(IntPtr handle) : base(handle) { }
    }

    partial class HeaderPage
    {
        public UILabel TextHeader => txtHeader;
        public UIImageView ImageIconHeader => imgHeader;
        public UIView AreaViewTouch => viewTouchArea;

        public UIView AreaViewTouchRight => viewTouchAreRight;
        public UIImageView ImageRight => imgRightMenu;

    }
}
