// This file has been autogenerated from a class added in the UI designer.

using System;
using iOS.Page.BasePage;
using Core.ViewModels;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using UIKit;
using Int.iOS.Factories.Adapter;
using Core.Models.DAL;
using System.Collections.Generic;

namespace iOS.Storyboard
{
    public partial class Comunication : BasePageSideMenu<ComunicationViewModel>
    {

        private ComponentViewSource<IItemComunication> _source;
        public Comunication(IntPtr handle) : base(handle) { }

        protected override void BindViews()
        {
            base.BindViews();

            _source = ComponentViewSourceFactory.CreateForTable(nameof(ComunicationCell),
                                                                new List<IItemComunication>(),
                                                                TableView,
                                                                crossCellModel:
                                                                new ComunicationViewModel.ComunicationCell(ModelView));

            TableView.Source = _source;
            _source.AutoResize();
        }
    }

    partial class Comunication
    {
        [CrossView(nameof(ComunicationViewModel.ListView))]
        UITableView propname1 => TableView;
    }
}
