// This file has been autogenerated from a class added in the UI designer.

using System;
using iOS.Page.BasePage;
using Core.ViewModels;
using Core.Models.DAL.Contacts;
using System.Collections.Generic;
using Int.iOS.Factories.Adapter;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using UIKit;

namespace iOS.Storyboard
{
    public partial class Contact : BasePageSideMenu<ContactViewModel>
    {
        public Contact(IntPtr handle) : base(handle) { }

        protected override void BindViews()
        {
            base.BindViews();

            var sourceYour = ComponentViewSourceFactory.CreateForTable(nameof(ContactCell),
                                                                       new List<IItemContact>(),
                                                                       TableView,
                                                                       crossCellModel: new ContactViewModel.ContactCell(ModelView));
            TableView.Source = sourceYour;
        }
    }

    partial class Contact
    {
        [CrossView(nameof(ContactViewModel.ListViewYour))]
        UITableView propname1 => TableView;
    }
}
