// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.ViewModels;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using iOS.Page.BasePage;
using UIKit;

namespace iOS.Storyboard
{
    public partial class Dashboard : BasePageSideMenu<DashboardViewModel>
    {
        public Dashboard(IntPtr handle) : base(handle) { }
    }

    partial class Dashboard
    {
        [CrossView(nameof(DashboardViewModel.WelcomeText))]
        UILabel propName1 => lblWelcome;

        [CrossView(nameof(DashboardViewModel.NameSurnameText))]
        UILabel propName2 => lblNameClient;

        [CrossView(nameof(DashboardViewModel.BackgroundImage))]
        UIImageView propName3 => imgRoot;
    }
}
