// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.ViewModels;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Extensions;
using iOS.Page.BasePage;
using UIKit;

namespace iOS.Storyboard
{
    public partial class Login : BasePage<LoginViewModel>
    {
        public Login(IntPtr handle) : base(handle) { }

        protected override void BindViews()
        {
            base.BindViews();

            txtUsername.ResponderNext(txtPassword, null);
            txtPassword.ResponderNext(null, null);
        }
    }

    partial class Login
    {
        [CrossView(nameof(LoginViewModel.BackgroundImageView))]
        UIImageView BackgroundImageView => imgBackround;

        [CrossView(nameof(LoginViewModel.EmailTextView))]
        UITextField txtUsernameCross => txtUsername;

        [CrossView(nameof(LoginViewModel.PasswordTextView))]
        UITextField txtPasswordCross => txtPassword;

        [CrossView(nameof(LoginViewModel.LoginButton))]
        UILabel btnOKCross => btnOK;

        [CrossView(nameof(LoginViewModel.ForgotPasswordTextView))]
        UILabel btnForgotCross => btnForgot;

        [CrossView(nameof(LoginViewModel.ImageView))]
        UIImageView imageLogoCross => imgLogo;

        [CrossView(nameof(LoginViewModel.RememberMeImageView))]
        UIImageView imgRememberCross => imgRemember;

        [CrossView(nameof(LoginViewModel.RememberMeTextView))]
        UILabel lblRememberCross => lblRemember;

        [CrossView(nameof(LoginViewModel.RememberMeTouchArea))]
        UIView viewRememberMyAreaCross => viewRememberMyArea;

        [CrossView(nameof(LoginViewModel.ForgotPasswordUndeline))]
        UIView ForgotPasswordUndeline => viewForgotPasswordUnderline;

        [CrossView(nameof(LoginViewModel.BackgroundUsername))]
        UIView BackgroundUsername => viewBackgroundUsername;

        [CrossView(nameof(LoginViewModel.BackgroundPassword))]
        UIView BackgroundPassword => viewBackgroundPassword;
    }
}