// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.ViewModels;
using iOS.Page.BasePage;

namespace iOS.Storyboard
{
    public partial class Splash : BasePage<SplashViewModel>
    {
        public Splash(IntPtr handle) : base(handle) { }
    }
}
