// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.Models.DAL;
using Core.ViewModels;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter.CellView;
using UIKit;

namespace iOS.Storyboard
{
    //public partial class ComunicationCell : ComponentTableViewCell<IItemComunication>
    //{
    //    public ComunicationCell(IntPtr handle) : base(handle) { }

    //    [CrossView(nameof(UserAddedBooksViewModel.ComunicationCell.CellContentRootView))]
    //    UIView propname1 => viewMain;

    //    [CrossView(nameof(UserAddedBooksViewModel.ComunicationCell.ComunicationText))]
    //    UILabel propname2 => lblContent;

    //    [CrossView(nameof(UserAddedBooksViewModel.ComunicationCell.ComunicationDate))]
    //    UITextField propname3 => lblDate;
    //}
}
