// This file has been autogenerated from a class added in the UI designer.

using System;
using Int.iOS.Factories.Adapter.CellView;
using Core.Models.DAL.Account;
using Core.ViewModels.Account;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using UIKit;

namespace iOS.Storyboard
{
    public partial class AccountCell : ComponentTableViewCell<ItemAccount>
    {
        public AccountCell(IntPtr handle) : base(handle) { }

        [CrossView(nameof(AccountViewModel.AccountCell.CellContentRootView))]
        UIView propname1 => Root;

        [CrossView(nameof(AccountViewModel.AccountCell.Name))]
        UILabel propname2 => lblName;

        [CrossView(nameof(AccountViewModel.AccountCell.Value))]
        UITextView propname3 => txt2Value;

        [CrossView(nameof(AccountViewModel.AccountCell.DashView))]
        UIView propname4 => viewLine;
    }
}
