// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.Models.DAL.Contacts;
using Core.ViewModels;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter.CellView;
using UIKit;

namespace iOS.Storyboard
{
    public partial class ContactCell : ComponentTableViewCell<IItemContact>
    {
        public ContactCell(IntPtr handle) : base(handle) { }

        [CrossView(nameof(ContactViewModel.ContactCell.DashView))]
        UIView propname1 => viewLine;

        [CrossView(nameof(ContactViewModel.ContactCell.Value))]
        UILabel propname2 => lblValue;

        [CrossView(nameof(ContactViewModel.ContactCell.Label))]
        UILabel propname3 => lblLabel;

        [CrossView(nameof(ContactViewModel.ContactCell.ContactAction))]
        UILabel propname4 => lblCall;
    }
}
