// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Core.Models.DAL.Account;
using Core.ViewModels.Account;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter;
using iOS.Page.BasePage;
using iOS.Views.Cell.Account;
using UIKit;
using Int.iOS;

namespace iOS.Storyboard
{
    public partial class Account : BasePageSideMenu<AccountViewModel>
    {
        public Account(IntPtr handle) : base(handle) { }

        protected override void BindViews()
        {
            base.BindViews();

            var sourceYour = ComponentViewSourceFactory.CreateForTable(nameof(AccountCell),
                                                                   new List<ItemAccount>(),
                                                                   TableViewYour,
                                                                   crossCellModel: new AccountViewModel.AccountCell(ModelView));
            this.btnChangePassword.Superview.SetNeedsLayout();
            this.btnChangePassword.Superview.LayoutIfNeeded();

            sourceYour.AddFooterView(new AccountSaveData(), (float)btnChangePassword.Frame.Height);

            TableViewYour.Source = sourceYour;

            switch (AppTools.IphoneSizeAfter())
            {
                case IphoneType.IPhoneSe:
                    DinamicHeight(6.8f);
                    break;
                case IphoneType.IPhnoneNormal:
                    DinamicHeight(8f);
                    break;
                case IphoneType.IPhonePlus:
                    DinamicHeight(8.8f);
                    break;
            }
        }

        private void DinamicHeight(float procent)
        {
            heightTable.Constant = 6f * UIScreen.MainScreen.Bounds.Height / procent;
        }
    }

    partial class Account
    {
        [CrossView(nameof(AccountViewModel.ListViewYour))]
        UITableView propname1 => TableViewYour;

        [CrossView(nameof(AccountViewModel.ChangePasswordText))]
        UILabel propname2 => btnChangePassword;
    }
}
