// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.ViewModels.Account;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Extensions;
using iOS.Page.BasePage;
using UIKit;

namespace iOS.Storyboard
{
    public partial class AccountDescriptions : BasePageSideMenu<AccountDescriptionsViewModel>
    {
        public AccountDescriptions(IntPtr handle) : base(handle) { }

        protected override void BindViews()
        {
            base.BindViews();

            txtOld.ResponderNext(txtNew, null);
            txtNew.ResponderNext(txtConfirm, null);
            txtConfirm.ResponderNext(null, null);
        }
    }

    partial class AccountDescriptions
    {

        [CrossView(nameof(AccountDescriptionsViewModel.OldPassword))]
        UITextField propname1 => txtOld;

        [CrossView(nameof(AccountDescriptionsViewModel.NewPasswordText))]
        UITextField propname2 => txtNew;

        [CrossView(nameof(AccountDescriptionsViewModel.ConfirmPasswordText))]
        UITextField propname3 => txtConfirm;

        [CrossView(nameof(AccountDescriptionsViewModel.LineNewView))]
        UIView propname4 => viewLineNew;

        [CrossView(nameof(AccountDescriptionsViewModel.LineConfirmView))]
        UIView propname5 => viewConfirm;

        [CrossView(nameof(AccountDescriptionsViewModel.ContainerView))]
        UIView propname6 => mainView;

        [CrossView(nameof(AccountDescriptionsViewModel.ButtonConfirmText))]
        UILabel propname7 => btnConfirm;

        [CrossView(nameof(AccountDescriptionsViewModel.LineOldView))]
        UIView propname8 => viewLineOld;
    }
}
