// This file has been autogenerated from a class added in the UI designer.

using System;
using Int.iOS.Views;

namespace iOS.Storyboard
{
    public partial class ConcreteUIShadowCastingView : UIShadowCastingView
    {
        public ConcreteUIShadowCastingView(IntPtr handle) : base(handle) { }
    }
}
