// This file has been autogenerated from a class added in the UI designer.

using System;
using Int.iOS.Factories.Adapter.CellView;
using Core.Models.DAL;
using UIKit;

namespace iOS.Storyboard
{
    public partial class ProductChildCell : ComponentTableViewCell<IProduct>
    {
        public ProductChildCell(IntPtr handle) : base(handle) { }

        public UILabel ProducDocName => lblName;
        public UILabel ProductDocValue => lblValue;

        public UIImageView ImagePdf => imgPdf;
        public UILabel PdfValue => lblPdf;

        public UIView ViewCell => viewCellChild;
        public UIView ViewLineCell => viewLineDoc;

    }
}
