// This file has been autogenerated from a class added in the UI designer.

using System;
using Int.iOS.Factories.Adapter.V2;
using Core.Models.DAL;
using UIKit;

namespace iOS.Storyboard
{
    public partial class ProductHeaderCell : UIExpandableTableViewHeaderCell<IItemProducts>
    {
        public ProductHeaderCell(IntPtr handle) : base(handle) { }

        public UILabel ProductName => lblName;
        public UILabel ProductCode => lblValue;
        public UIImageView ImageArrow => imgArrow;

        public UIView ViewCell => viewCell;
        public UIView ViewLineCell => viewLineHeader;

        public UIView FooterView => viewLastView;
    }
}
